// authorize.proto — canonical API contract for the Arrowhead AuthorizationPDP service.
//
// This file is the single source of truth for the interface between a Policy
// Enforcement Point (PEP, e.g. DynamicOrchestration) and a Policy Decision
// Point (PDP, e.g. AuthzForce CE or any XACML-compatible engine).
//
// Design basis: OASIS XACML 3.0 Request/Response model, expressed as gRPC.
// Reference: https://docs.oasis-open.org/xacml/xacml-json-http/v1.1/
//
// XACML attribute mapping:
//   subject  → XACML subject-category / subject-id
//   service  → XACML resource-category / resource-id
//   provider → XACML resource-category / urn:arrowhead:attribute:provider-id (optional)
//   action   → XACML action-category   / action-id
//
// Namespace separation (no string-encoding hacks):
//   Orchestration decisions  →  action = "orchestrate", provider set
//   Enforcement decisions    →  action = "consume",     provider empty
//
// Code generation (requires protoc + plugins):
//   make -C core-evol/proto/authorize gen
//
// grpcurl inspection (requires running authz-pdp with GRPC_REFLECTION=true):
//   grpcurl -plaintext localhost:9550 list
//   grpcurl -plaintext localhost:9550 describe arrowhead.authz.v1.AuthorizationPDP
//   grpcurl -plaintext -d '{"subject":"portal-cloud-ml","service":"telemetry","provider":"robot-fleet-site-1","action":"orchestrate"}' \
//     localhost:9550 arrowhead.authz.v1.AuthorizationPDP/Decide

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.24.4
// source: authorize.proto

package authorize

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Decision mirrors the XACML 3.0 Decision element values.
// Reference: XACML 3.0 §7.17
type Decision int32

const (
	// DECISION_UNSPECIFIED is the zero value; treat as DENY.
	Decision_DECISION_UNSPECIFIED Decision = 0
	// PERMIT: the PDP grants the requested access. The PEP may proceed.
	Decision_PERMIT Decision = 1
	// DENY: the PDP denies the requested access. The PEP must block.
	Decision_DENY Decision = 2
	// INDETERMINATE: the PDP could not evaluate the request (error, missing
	// attribute, policy syntax error). PEPs MUST treat as DENY (fail-closed).
	Decision_INDETERMINATE Decision = 3
	// NOT_APPLICABLE: no policy matched the request. Typically treated as DENY
	// under a deny-unless-permit combining algorithm.
	Decision_NOT_APPLICABLE Decision = 4
)

// Enum value maps for Decision.
var (
	Decision_name = map[int32]string{
		0: "DECISION_UNSPECIFIED",
		1: "PERMIT",
		2: "DENY",
		3: "INDETERMINATE",
		4: "NOT_APPLICABLE",
	}
	Decision_value = map[string]int32{
		"DECISION_UNSPECIFIED": 0,
		"PERMIT":               1,
		"DENY":                 2,
		"INDETERMINATE":        3,
		"NOT_APPLICABLE":       4,
	}
)

func (x Decision) Enum() *Decision {
	p := new(Decision)
	*p = x
	return p
}

func (x Decision) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Decision) Descriptor() protoreflect.EnumDescriptor {
	return file_authorize_proto_enumTypes[0].Descriptor()
}

func (Decision) Type() protoreflect.EnumType {
	return &file_authorize_proto_enumTypes[0]
}

func (x Decision) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Decision.Descriptor instead.
func (Decision) EnumDescriptor() ([]byte, []int) {
	return file_authorize_proto_rawDescGZIP(), []int{0}
}

// DecisionRequest carries the access-control context for a single evaluation.
// Corresponds to the XACML 3.0 <Request> element.
type DecisionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// domain_id is the XACML policy domain identifier (AuthzForce domain UUID or
	// external name). Used in multi-tenant deployments. May be left empty if the
	// PDP is pre-configured with a single domain.
	DomainId string `protobuf:"bytes,1,opt,name=domain_id,json=domainId,proto3" json:"domain_id,omitempty"`
	// subject is the XACML subject-id — the system requesting access.
	// Typically the consumer's systemName as registered in the ServiceRegistry.
	// Maps to: XACML subject-category urn:oasis:names:tc:xacml:1.0:subject:subject-id
	Subject string `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	// service is the service definition name — the resource being accessed.
	// Maps to: XACML resource-category urn:oasis:names:tc:xacml:1.0:resource:resource-id
	// Example: "telemetry", "telemetry-rest"
	Service string `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`
	// provider is the provider system name. When set, the PDP evaluates a
	// per-provider policy. When empty, the decision is service-level only.
	//
	// Sending provider allows the policy to distinguish:
	//
	//	Permit(consumer, telemetry, robot-fleet-site-1)   ← allow site-1 only
	//	Deny  (consumer, telemetry, robot-fleet-site-2)   ← deny site-2
	//
	// Maps to: XACML resource-category urn:arrowhead:attribute:provider-id
	// Set by:  orchestration PEPs (DynamicOrchestration)
	// Absent:  enforcement PEPs (kafka-authz, pki-rest-authz, topic-auth-xacml)
	Provider string `protobuf:"bytes,4,opt,name=provider,proto3" json:"provider,omitempty"`
	// action is the operation being requested.
	// Maps to: XACML action-category urn:oasis:names:tc:xacml:1.0:action:action-id
	//
	// Conventional values:
	//
	//	"orchestrate" — orchestration PEP requesting provider endpoint disclosure
	//	"consume"     — enforcement PEP requesting data-plane access
	//
	// Using distinct action values provides clean namespace separation: an
	// orchestration policy (action=orchestrate) never matches an enforcement
	// request (action=consume) and vice versa.
	Action string `protobuf:"bytes,5,opt,name=action,proto3" json:"action,omitempty"`
}

func (x *DecisionRequest) Reset() {
	*x = DecisionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authorize_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DecisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecisionRequest) ProtoMessage() {}

func (x *DecisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authorize_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecisionRequest.ProtoReflect.Descriptor instead.
func (*DecisionRequest) Descriptor() ([]byte, []int) {
	return file_authorize_proto_rawDescGZIP(), []int{0}
}

func (x *DecisionRequest) GetDomainId() string {
	if x != nil {
		return x.DomainId
	}
	return ""
}

func (x *DecisionRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *DecisionRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *DecisionRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *DecisionRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

// DecisionResponse carries the PDP's evaluation result.
// Corresponds to the XACML 3.0 <Response> element.
type DecisionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// decision is the PDP's access-control decision.
	// A PEP MUST treat any value other than PERMIT as denial.
	Decision Decision `protobuf:"varint,1,opt,name=decision,proto3,enum=arrowhead.authz.v1.Decision" json:"decision,omitempty"`
	// status_code is the XACML status code URN for the evaluation.
	// Informational; PEPs should act on decision, not status_code.
	// Example: "urn:oasis:names:tc:xacml:1.0:status:ok"
	//
	//	"urn:oasis:names:tc:xacml:1.0:status:processing-error"
	StatusCode string `protobuf:"bytes,2,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
}

func (x *DecisionResponse) Reset() {
	*x = DecisionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_authorize_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DecisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecisionResponse) ProtoMessage() {}

func (x *DecisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authorize_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecisionResponse.ProtoReflect.Descriptor instead.
func (*DecisionResponse) Descriptor() ([]byte, []int) {
	return file_authorize_proto_rawDescGZIP(), []int{1}
}

func (x *DecisionResponse) GetDecision() Decision {
	if x != nil {
		return x.Decision
	}
	return Decision_DECISION_UNSPECIFIED
}

func (x *DecisionResponse) GetStatusCode() string {
	if x != nil {
		return x.StatusCode
	}
	return ""
}

var File_authorize_proto protoreflect.FileDescriptor

var file_authorize_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x12, 0x61, 0x72, 0x72, 0x6f, 0x77, 0x68, 0x65, 0x61, 0x64, 0x2e, 0x61, 0x75, 0x74,
	0x68, 0x7a, 0x2e, 0x76, 0x31, 0x22, 0x96, 0x01, 0x0a, 0x0f, 0x44, 0x65, 0x63, 0x69, 0x73, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x6f, 0x6d,
	0x61, 0x69, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x6f,
	0x6d, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72,
	0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x72,
	0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x6d,
	0x0a, 0x10, 0x44, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x38, 0x0a, 0x08, 0x64, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x61, 0x72, 0x72, 0x6f, 0x77, 0x68, 0x65, 0x61, 0x64,
	0x2e, 0x61, 0x75, 0x74, 0x68, 0x7a, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x63, 0x69, 0x73, 0x69,
	0x6f, 0x6e, 0x52, 0x08, 0x64, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x0a, 0x0b,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x2a, 0x61, 0x0a,
	0x08, 0x44, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x14, 0x44, 0x45, 0x43,
	0x49, 0x53, 0x49, 0x4f, 0x4e, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45,
	0x44, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x50, 0x45, 0x52, 0x4d, 0x49, 0x54, 0x10, 0x01, 0x12,
	0x08, 0x0a, 0x04, 0x44, 0x45, 0x4e, 0x59, 0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d, 0x49, 0x4e, 0x44,
	0x45, 0x54, 0x45, 0x52, 0x4d, 0x49, 0x4e, 0x41, 0x54, 0x45, 0x10, 0x03, 0x12, 0x12, 0x0a, 0x0e,
	0x4e, 0x4f, 0x54, 0x5f, 0x41, 0x50, 0x50, 0x4c, 0x49, 0x43, 0x41, 0x42, 0x4c, 0x45, 0x10, 0x04,
	0x32, 0x67, 0x0a, 0x10, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x50, 0x44, 0x50, 0x12, 0x53, 0x0a, 0x06, 0x44, 0x65, 0x63, 0x69, 0x64, 0x65, 0x12, 0x23,
	0x2e, 0x61, 0x72, 0x72, 0x6f, 0x77, 0x68, 0x65, 0x61, 0x64, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x7a,
	0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x61, 0x72, 0x72, 0x6f, 0x77, 0x68, 0x65, 0x61, 0x64, 0x2e,
	0x61, 0x75, 0x74, 0x68, 0x7a, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2f, 0x5a, 0x2d, 0x61, 0x72, 0x72,
	0x6f, 0x77, 0x68, 0x65, 0x61, 0x64, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2d, 0x65, 0x76, 0x6f, 0x6c,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65,
	0x3b, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_authorize_proto_rawDescOnce sync.Once
	file_authorize_proto_rawDescData = file_authorize_proto_rawDesc
)

func file_authorize_proto_rawDescGZIP() []byte {
	file_authorize_proto_rawDescOnce.Do(func() {
		file_authorize_proto_rawDescData = protoimpl.X.CompressGZIP(file_authorize_proto_rawDescData)
	})
	return file_authorize_proto_rawDescData
}

var file_authorize_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_authorize_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_authorize_proto_goTypes = []any{
	(Decision)(0),            // 0: arrowhead.authz.v1.Decision
	(*DecisionRequest)(nil),  // 1: arrowhead.authz.v1.DecisionRequest
	(*DecisionResponse)(nil), // 2: arrowhead.authz.v1.DecisionResponse
}
var file_authorize_proto_depIdxs = []int32{
	0, // 0: arrowhead.authz.v1.DecisionResponse.decision:type_name -> arrowhead.authz.v1.Decision
	1, // 1: arrowhead.authz.v1.AuthorizationPDP.Decide:input_type -> arrowhead.authz.v1.DecisionRequest
	2, // 2: arrowhead.authz.v1.AuthorizationPDP.Decide:output_type -> arrowhead.authz.v1.DecisionResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_authorize_proto_init() }
func file_authorize_proto_init() {
	if File_authorize_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_authorize_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*DecisionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_authorize_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*DecisionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_authorize_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_authorize_proto_goTypes,
		DependencyIndexes: file_authorize_proto_depIdxs,
		EnumInfos:         file_authorize_proto_enumTypes,
		MessageInfos:      file_authorize_proto_msgTypes,
	}.Build()
	File_authorize_proto = out.File
	file_authorize_proto_rawDesc = nil
	file_authorize_proto_goTypes = nil
	file_authorize_proto_depIdxs = nil
}
