// authorize.proto — canonical API contract for the Arrowhead AuthorizationPDP service.
//
// This file is the single source of truth for the interface between a Policy
// Enforcement Point (PEP, e.g. DynamicOrchestration) and a Policy Decision
// Point (PDP, e.g. AuthzForce CE or any XACML-compatible engine).
//
// Design basis: OASIS XACML 3.0 Request/Response model, expressed as gRPC.
// Reference: https://docs.oasis-open.org/xacml/xacml-json-http/v1.1/
//
// XACML attribute mapping:
//   subject  → XACML subject-category / subject-id
//   service  → XACML resource-category / resource-id
//   provider → XACML resource-category / urn:arrowhead:attribute:provider-id (optional)
//   action   → XACML action-category   / action-id
//
// Namespace separation (no string-encoding hacks):
//   Orchestration decisions  →  action = "orchestrate", provider set
//   Enforcement decisions    →  action = "consume",     provider empty
//
// Code generation (requires protoc + plugins):
//   make -C core-evol/proto/authorize gen
//
// grpcurl inspection (requires running authz-pdp with GRPC_REFLECTION=true):
//   grpcurl -plaintext localhost:9550 list
//   grpcurl -plaintext localhost:9550 describe arrowhead.authz.v1.AuthorizationPDP
//   grpcurl -plaintext -d '{"subject":"portal-cloud-ml","service":"telemetry","provider":"robot-fleet-site-1","action":"orchestrate"}' \
//     localhost:9550 arrowhead.authz.v1.AuthorizationPDP/Decide

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v4.24.4
// source: authorize.proto

package authorize

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	AuthorizationPDP_Decide_FullMethodName = "/arrowhead.authz.v1.AuthorizationPDP/Decide"
)

// AuthorizationPDPClient is the client API for AuthorizationPDP service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AuthorizationPDP is the Policy Decision Point interface.
//
// A PEP (e.g. DynamicOrchestration, kafka-authz, pki-rest-authz) calls Decide
// once per resource access attempt. The PDP evaluates the request against its
// policy store and returns a Decision.
//
// Implementations:
//   - authz-pdp (core-evol/cmd/authz-pdp): gRPC adapter backed by AuthzForce CE
//   - Any XACML-compatible PDP that implements this interface
type AuthorizationPDPClient interface {
	// Decide evaluates a single access-control request.
	//
	// The PEP sends a DecisionRequest describing who is accessing what with which
	// action. The PDP evaluates the applicable policies and returns a Decision.
	//
	// Failure semantics (fail-closed): if the PDP returns an error or
	// INDETERMINATE, the PEP MUST treat it as DENY and exclude the resource.
	//
	// Latency / caching: the PDP MAY cache decisions. The recommended TTL is
	// 0 (no cache) for orchestration decisions — stale permits survive revocation.
	// Enforcement PEPs MAY use a short TTL (e.g. 5 s) to reduce latency under
	// high throughput, accepting a bounded revocation lag.
	Decide(ctx context.Context, in *DecisionRequest, opts ...grpc.CallOption) (*DecisionResponse, error)
}

type authorizationPDPClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthorizationPDPClient(cc grpc.ClientConnInterface) AuthorizationPDPClient {
	return &authorizationPDPClient{cc}
}

func (c *authorizationPDPClient) Decide(ctx context.Context, in *DecisionRequest, opts ...grpc.CallOption) (*DecisionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DecisionResponse)
	err := c.cc.Invoke(ctx, AuthorizationPDP_Decide_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthorizationPDPServer is the server API for AuthorizationPDP service.
// All implementations must embed UnimplementedAuthorizationPDPServer
// for forward compatibility
//
// AuthorizationPDP is the Policy Decision Point interface.
//
// A PEP (e.g. DynamicOrchestration, kafka-authz, pki-rest-authz) calls Decide
// once per resource access attempt. The PDP evaluates the request against its
// policy store and returns a Decision.
//
// Implementations:
//   - authz-pdp (core-evol/cmd/authz-pdp): gRPC adapter backed by AuthzForce CE
//   - Any XACML-compatible PDP that implements this interface
type AuthorizationPDPServer interface {
	// Decide evaluates a single access-control request.
	//
	// The PEP sends a DecisionRequest describing who is accessing what with which
	// action. The PDP evaluates the applicable policies and returns a Decision.
	//
	// Failure semantics (fail-closed): if the PDP returns an error or
	// INDETERMINATE, the PEP MUST treat it as DENY and exclude the resource.
	//
	// Latency / caching: the PDP MAY cache decisions. The recommended TTL is
	// 0 (no cache) for orchestration decisions — stale permits survive revocation.
	// Enforcement PEPs MAY use a short TTL (e.g. 5 s) to reduce latency under
	// high throughput, accepting a bounded revocation lag.
	Decide(context.Context, *DecisionRequest) (*DecisionResponse, error)
	mustEmbedUnimplementedAuthorizationPDPServer()
}

// UnimplementedAuthorizationPDPServer must be embedded to have forward compatible implementations.
type UnimplementedAuthorizationPDPServer struct {
}

func (UnimplementedAuthorizationPDPServer) Decide(context.Context, *DecisionRequest) (*DecisionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Decide not implemented")
}
func (UnimplementedAuthorizationPDPServer) mustEmbedUnimplementedAuthorizationPDPServer() {}

// UnsafeAuthorizationPDPServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthorizationPDPServer will
// result in compilation errors.
type UnsafeAuthorizationPDPServer interface {
	mustEmbedUnimplementedAuthorizationPDPServer()
}

func RegisterAuthorizationPDPServer(s grpc.ServiceRegistrar, srv AuthorizationPDPServer) {
	s.RegisterService(&AuthorizationPDP_ServiceDesc, srv)
}

func _AuthorizationPDP_Decide_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizationPDPServer).Decide(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthorizationPDP_Decide_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizationPDPServer).Decide(ctx, req.(*DecisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthorizationPDP_ServiceDesc is the grpc.ServiceDesc for AuthorizationPDP service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthorizationPDP_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "arrowhead.authz.v1.AuthorizationPDP",
	HandlerType: (*AuthorizationPDPServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Decide",
			Handler:    _AuthorizationPDP_Decide_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "authorize.proto",
}
