// certlifecycle.proto — canonical API contract for the Arrowhead
// CertificateLifecycle service.
//
// This file is the single source of truth for the interface between the
// profile-ca (certificate authority, server) and any subscriber (e.g. PIP,
// audit log, monitoring). It is the second gRPC interface in the ADAPT stack,
// following authorize.proto.
//
// Design basis: event-driven certificate lifecycle — issued, revoked, expired.
// Subscribers receive a snapshot of current state on connect, then live events.
//
// XACML attribute mapping for cert-level enrichment:
//   cn → XACML subject-category / subject-id
//   ou → XACML subject-category / urn:arrowhead:attribute:cert-level
//        values: "lo" (Local Cloud CA), "on" (Onboarding),
//                "de" (Device), "sy" (System — used for service mTLS)
//
// Code generation (requires protoc + plugins):
//   make -C core-evol/proto/certlifecycle gen
//
// grpcurl inspection (requires running profile-ca with GRPC reflection enabled):
//   grpcurl -plaintext localhost:8089 list
//   grpcurl -plaintext localhost:8089 describe arrowhead.ca.v1.CertificateLifecycle
//   grpcurl -plaintext -d '{"include_snapshot":true}' \
//     localhost:8089 arrowhead.ca.v1.CertificateLifecycle/Subscribe

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.24.4
// source: certlifecycle.proto

package certlifecycle

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EventType classifies the certificate lifecycle transition.
type EventType int32

const (
	// EVENT_UNSPECIFIED is the zero value; subscribers MUST ignore it.
	EventType_EVENT_UNSPECIFIED EventType = 0
	// ISSUED: a new certificate was issued by the CA.
	// Subscriber action: Register(cn, ou, valid=true)
	EventType_ISSUED EventType = 1
	// REVOKED: the certificate was explicitly revoked (DELETE /ca/certificates/{cn}).
	// Subscriber action: Register(cn, ou, valid=false)
	EventType_REVOKED EventType = 2
	// EXPIRED: the certificate passed its NotAfter time.
	// Subscriber action: Register(cn, ou, valid=false)
	EventType_EXPIRED EventType = 3
	// SNAPSHOT: current-state snapshot event sent before live events when
	// include_snapshot=true. Semantically identical to ISSUED but indicates
	// it is part of the initial baseline, not a real-time issuance.
	// Subscriber action: Register(cn, ou, valid=true)
	EventType_SNAPSHOT EventType = 4
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "EVENT_UNSPECIFIED",
		1: "ISSUED",
		2: "REVOKED",
		3: "EXPIRED",
		4: "SNAPSHOT",
	}
	EventType_value = map[string]int32{
		"EVENT_UNSPECIFIED": 0,
		"ISSUED":            1,
		"REVOKED":           2,
		"EXPIRED":           3,
		"SNAPSHOT":          4,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_certlifecycle_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_certlifecycle_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_certlifecycle_proto_rawDescGZIP(), []int{0}
}

// SubscribeRequest controls the initial delivery behaviour.
type SubscribeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// include_snapshot controls whether the server pre-populates the stream with
	// current state before switching to live events.
	//
	// true  — server sends one SNAPSHOT event per currently valid certificate,
	//
	//	then continues with live ISSUED/REVOKED/EXPIRED events.
	//	Use on first connect or after a reconnect to re-baseline.
	//
	// false — server sends only live events from this point forward.
	//
	//	Use when the subscriber already has accurate state and only wants
	//	incremental updates.
	IncludeSnapshot bool `protobuf:"varint,1,opt,name=include_snapshot,json=includeSnapshot,proto3" json:"include_snapshot,omitempty"`
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_certlifecycle_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_certlifecycle_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_certlifecycle_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeRequest) GetIncludeSnapshot() bool {
	if x != nil {
		return x.IncludeSnapshot
	}
	return false
}

// CertEvent describes a certificate lifecycle transition.
// Each event is self-contained — subscribers do not need to maintain
// history to interpret it.
type CertEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// cn is the certificate Common Name — the system identity.
	// Maps to: XACML subject-id
	// Example: "service-partner-1", "portal-cloud-ml"
	Cn string `protobuf:"bytes,1,opt,name=cn,proto3" json:"cn,omitempty"`
	// ou is the Arrowhead certificate profile tier encoded in the Subject OU.
	// Maps to: XACML urn:arrowhead:attribute:cert-level
	// Values (ordered by privilege):
	//
	//	"lo" — Local Cloud CA (root; not used for service identity)
	//	"on" — Onboarding (may request Device certs)
	//	"de" — Device (may request System certs)
	//	"sy" — System (used for service-to-service mTLS)
	Ou string `protobuf:"bytes,2,opt,name=ou,proto3" json:"ou,omitempty"`
	// type is the certificate lifecycle event type.
	Type EventType `protobuf:"varint,3,opt,name=type,proto3,enum=arrowhead.ca.v1.EventType" json:"type,omitempty"`
	// issued_at is the certificate issuance time in RFC3339 format.
	// Present for ISSUED and SNAPSHOT events. Empty for REVOKED/EXPIRED.
	IssuedAt string `protobuf:"bytes,4,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	// expires_at is the certificate expiry time in RFC3339 format.
	// Present for ISSUED and SNAPSHOT events. Used by subscribers to schedule
	// proactive cleanup. Empty for REVOKED/EXPIRED.
	ExpiresAt string `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
}

func (x *CertEvent) Reset() {
	*x = CertEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_certlifecycle_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CertEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertEvent) ProtoMessage() {}

func (x *CertEvent) ProtoReflect() protoreflect.Message {
	mi := &file_certlifecycle_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertEvent.ProtoReflect.Descriptor instead.
func (*CertEvent) Descriptor() ([]byte, []int) {
	return file_certlifecycle_proto_rawDescGZIP(), []int{1}
}

func (x *CertEvent) GetCn() string {
	if x != nil {
		return x.Cn
	}
	return ""
}

func (x *CertEvent) GetOu() string {
	if x != nil {
		return x.Ou
	}
	return ""
}

func (x *CertEvent) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_UNSPECIFIED
}

func (x *CertEvent) GetIssuedAt() string {
	if x != nil {
		return x.IssuedAt
	}
	return ""
}

func (x *CertEvent) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

var File_certlifecycle_proto protoreflect.FileDescriptor

var file_certlifecycle_proto_rawDesc = []byte{
	0x0a, 0x13, 0x63, 0x65, 0x72, 0x74, 0x6c, 0x69, 0x66, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x61, 0x72, 0x72, 0x6f, 0x77, 0x68, 0x65, 0x61, 0x64,
	0x2e, 0x63, 0x61, 0x2e, 0x76, 0x31, 0x22, 0x3d, 0x0a, 0x10, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72,
	0x69, 0x62, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x29, 0x0a, 0x10, 0x69, 0x6e,
	0x63, 0x6c, 0x75, 0x64, 0x65, 0x5f, 0x73, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x69, 0x6e, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x53, 0x6e, 0x61,
	0x70, 0x73, 0x68, 0x6f, 0x74, 0x22, 0x97, 0x01, 0x0a, 0x09, 0x43, 0x65, 0x72, 0x74, 0x45, 0x76,
	0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x63, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x63, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x75, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x6f, 0x75, 0x12, 0x2e, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x1a, 0x2e, 0x61, 0x72, 0x72, 0x6f, 0x77, 0x68, 0x65, 0x61, 0x64, 0x2e, 0x63, 0x61,
	0x2e, 0x76, 0x31, 0x2e, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73, 0x73, 0x75, 0x65, 0x64, 0x5f, 0x61, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x73, 0x73, 0x75, 0x65, 0x64, 0x41, 0x74,
	0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x5f, 0x61, 0x74, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x41, 0x74, 0x2a,
	0x56, 0x0a, 0x09, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x15, 0x0a, 0x11,
	0x45, 0x56, 0x45, 0x4e, 0x54, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45,
	0x44, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x49, 0x53, 0x53, 0x55, 0x45, 0x44, 0x10, 0x01, 0x12,
	0x0b, 0x0a, 0x07, 0x52, 0x45, 0x56, 0x4f, 0x4b, 0x45, 0x44, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07,
	0x45, 0x58, 0x50, 0x49, 0x52, 0x45, 0x44, 0x10, 0x03, 0x12, 0x0c, 0x0a, 0x08, 0x53, 0x4e, 0x41,
	0x50, 0x53, 0x48, 0x4f, 0x54, 0x10, 0x04, 0x32, 0x64, 0x0a, 0x14, 0x43, 0x65, 0x72, 0x74, 0x69,
	0x66, 0x69, 0x63, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x66, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x12,
	0x4c, 0x0a, 0x09, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x12, 0x21, 0x2e, 0x61,
	0x72, 0x72, 0x6f, 0x77, 0x68, 0x65, 0x61, 0x64, 0x2e, 0x63, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x53,
	0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1a, 0x2e, 0x61, 0x72, 0x72, 0x6f, 0x77, 0x68, 0x65, 0x61, 0x64, 0x2e, 0x63, 0x61, 0x2e, 0x76,
	0x31, 0x2e, 0x43, 0x65, 0x72, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x30, 0x01, 0x42, 0x37, 0x5a,
	0x35, 0x61, 0x72, 0x72, 0x6f, 0x77, 0x68, 0x65, 0x61, 0x64, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2d,
	0x65, 0x76, 0x6f, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x65, 0x72, 0x74, 0x6c,
	0x69, 0x66, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x3b, 0x63, 0x65, 0x72, 0x74, 0x6c, 0x69, 0x66,
	0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_certlifecycle_proto_rawDescOnce sync.Once
	file_certlifecycle_proto_rawDescData = file_certlifecycle_proto_rawDesc
)

func file_certlifecycle_proto_rawDescGZIP() []byte {
	file_certlifecycle_proto_rawDescOnce.Do(func() {
		file_certlifecycle_proto_rawDescData = protoimpl.X.CompressGZIP(file_certlifecycle_proto_rawDescData)
	})
	return file_certlifecycle_proto_rawDescData
}

var file_certlifecycle_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_certlifecycle_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_certlifecycle_proto_goTypes = []any{
	(EventType)(0),           // 0: arrowhead.ca.v1.EventType
	(*SubscribeRequest)(nil), // 1: arrowhead.ca.v1.SubscribeRequest
	(*CertEvent)(nil),        // 2: arrowhead.ca.v1.CertEvent
}
var file_certlifecycle_proto_depIdxs = []int32{
	0, // 0: arrowhead.ca.v1.CertEvent.type:type_name -> arrowhead.ca.v1.EventType
	1, // 1: arrowhead.ca.v1.CertificateLifecycle.Subscribe:input_type -> arrowhead.ca.v1.SubscribeRequest
	2, // 2: arrowhead.ca.v1.CertificateLifecycle.Subscribe:output_type -> arrowhead.ca.v1.CertEvent
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_certlifecycle_proto_init() }
func file_certlifecycle_proto_init() {
	if File_certlifecycle_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_certlifecycle_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*SubscribeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_certlifecycle_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CertEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_certlifecycle_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_certlifecycle_proto_goTypes,
		DependencyIndexes: file_certlifecycle_proto_depIdxs,
		EnumInfos:         file_certlifecycle_proto_enumTypes,
		MessageInfos:      file_certlifecycle_proto_msgTypes,
	}.Build()
	File_certlifecycle_proto = out.File
	file_certlifecycle_proto_rawDesc = nil
	file_certlifecycle_proto_goTypes = nil
	file_certlifecycle_proto_depIdxs = nil
}
