// certlifecycle.proto — canonical API contract for the Arrowhead
// CertificateLifecycle service.
//
// This file is the single source of truth for the interface between the
// profile-ca (certificate authority, server) and any subscriber (e.g. PIP,
// audit log, monitoring). It is the second gRPC interface in the ADAPT stack,
// following authorize.proto.
//
// Design basis: event-driven certificate lifecycle — issued, revoked, expired.
// Subscribers receive a snapshot of current state on connect, then live events.
//
// XACML attribute mapping for cert-level enrichment:
//   cn → XACML subject-category / subject-id
//   ou → XACML subject-category / urn:arrowhead:attribute:cert-level
//        values: "lo" (Local Cloud CA), "on" (Onboarding),
//                "de" (Device), "sy" (System — used for service mTLS)
//
// Code generation (requires protoc + plugins):
//   make -C core-evol/proto/certlifecycle gen
//
// grpcurl inspection (requires running profile-ca with GRPC reflection enabled):
//   grpcurl -plaintext localhost:8089 list
//   grpcurl -plaintext localhost:8089 describe arrowhead.ca.v1.CertificateLifecycle
//   grpcurl -plaintext -d '{"include_snapshot":true}' \
//     localhost:8089 arrowhead.ca.v1.CertificateLifecycle/Subscribe

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v4.24.4
// source: certlifecycle.proto

package certlifecycle

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	CertificateLifecycle_Subscribe_FullMethodName = "/arrowhead.ca.v1.CertificateLifecycle/Subscribe"
)

// CertificateLifecycleClient is the client API for CertificateLifecycle service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CertificateLifecycle is the profile-ca → subscriber event stream interface.
//
// A subscriber (e.g. PIP) calls Subscribe once. The server streams CertEvents
// as they occur. If include_snapshot=true in the request, the server first
// streams all currently valid certificates (type=SNAPSHOT) before switching to
// live events. This allows subscribers to bootstrap from scratch without a
// separate REST call.
//
// Reconnect semantics: if the stream is interrupted, the subscriber SHOULD
// reconnect with include_snapshot=true to re-baseline its state. The server
// imposes no rate limit on reconnects.
//
// Failure semantics (fail-closed): if the subscriber cannot reach profile-ca,
// it MUST continue serving its last known state and NOT purge its store.
// Authorization decisions made while the stream is down use stale-but-not-empty
// cert-level attributes, which is safer than denying everything.
type CertificateLifecycleClient interface {
	// Subscribe opens a persistent server-side stream of CertEvents.
	//
	// The stream remains open until the client cancels or the server shuts down.
	// Subscribers should run this in a loop with exponential backoff reconnect.
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (CertificateLifecycle_SubscribeClient, error)
}

type certificateLifecycleClient struct {
	cc grpc.ClientConnInterface
}

func NewCertificateLifecycleClient(cc grpc.ClientConnInterface) CertificateLifecycleClient {
	return &certificateLifecycleClient{cc}
}

func (c *certificateLifecycleClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (CertificateLifecycle_SubscribeClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CertificateLifecycle_ServiceDesc.Streams[0], CertificateLifecycle_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &certificateLifecycleSubscribeClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CertificateLifecycle_SubscribeClient interface {
	Recv() (*CertEvent, error)
	grpc.ClientStream
}

type certificateLifecycleSubscribeClient struct {
	grpc.ClientStream
}

func (x *certificateLifecycleSubscribeClient) Recv() (*CertEvent, error) {
	m := new(CertEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CertificateLifecycleServer is the server API for CertificateLifecycle service.
// All implementations must embed UnimplementedCertificateLifecycleServer
// for forward compatibility
//
// CertificateLifecycle is the profile-ca → subscriber event stream interface.
//
// A subscriber (e.g. PIP) calls Subscribe once. The server streams CertEvents
// as they occur. If include_snapshot=true in the request, the server first
// streams all currently valid certificates (type=SNAPSHOT) before switching to
// live events. This allows subscribers to bootstrap from scratch without a
// separate REST call.
//
// Reconnect semantics: if the stream is interrupted, the subscriber SHOULD
// reconnect with include_snapshot=true to re-baseline its state. The server
// imposes no rate limit on reconnects.
//
// Failure semantics (fail-closed): if the subscriber cannot reach profile-ca,
// it MUST continue serving its last known state and NOT purge its store.
// Authorization decisions made while the stream is down use stale-but-not-empty
// cert-level attributes, which is safer than denying everything.
type CertificateLifecycleServer interface {
	// Subscribe opens a persistent server-side stream of CertEvents.
	//
	// The stream remains open until the client cancels or the server shuts down.
	// Subscribers should run this in a loop with exponential backoff reconnect.
	Subscribe(*SubscribeRequest, CertificateLifecycle_SubscribeServer) error
	mustEmbedUnimplementedCertificateLifecycleServer()
}

// UnimplementedCertificateLifecycleServer must be embedded to have forward compatible implementations.
type UnimplementedCertificateLifecycleServer struct {
}

func (UnimplementedCertificateLifecycleServer) Subscribe(*SubscribeRequest, CertificateLifecycle_SubscribeServer) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedCertificateLifecycleServer) mustEmbedUnimplementedCertificateLifecycleServer() {}

// UnsafeCertificateLifecycleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CertificateLifecycleServer will
// result in compilation errors.
type UnsafeCertificateLifecycleServer interface {
	mustEmbedUnimplementedCertificateLifecycleServer()
}

func RegisterCertificateLifecycleServer(s grpc.ServiceRegistrar, srv CertificateLifecycleServer) {
	s.RegisterService(&CertificateLifecycle_ServiceDesc, srv)
}

func _CertificateLifecycle_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CertificateLifecycleServer).Subscribe(m, &certificateLifecycleSubscribeServer{ServerStream: stream})
}

type CertificateLifecycle_SubscribeServer interface {
	Send(*CertEvent) error
	grpc.ServerStream
}

type certificateLifecycleSubscribeServer struct {
	grpc.ServerStream
}

func (x *certificateLifecycleSubscribeServer) Send(m *CertEvent) error {
	return x.ServerStream.SendMsg(m)
}

// CertificateLifecycle_ServiceDesc is the grpc.ServiceDesc for CertificateLifecycle service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CertificateLifecycle_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "arrowhead.ca.v1.CertificateLifecycle",
	HandlerType: (*CertificateLifecycleServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _CertificateLifecycle_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "certlifecycle.proto",
}
